<?php
if($status=='On'){
	if(apcu_fetch('skodi')=='Off')sw('kodi','On');
	if(apcu_fetch('sdenon')=='Off')sw('denon','On');
	if(apcu_fetch('stv')=='Off')sw('tv','On');
	if(apcu_fetch('zon')<100&&apcu_fetch('stvled')=='Off')sw('tvled','On');
	$ctx=stream_context_create(array('http'=>array('timeout'=>3)));
	file_get_contents('http://192.168.2.4/MainZone/index.put.asp?cmd0=PutZone_InputFunction/DVD',false,$ctx);
	usleep(800000);
	file_get_contents('http://192.168.2.4/MainZone/index.put.asp?cmd0=PutMasterVolumeSet/-40.0',false,$ctx);
	sleep(1);
}