<?php
if($s['denon']=='Off')sw(apcu_fetch('idenon'),'On','Denon');
if($s['tv']=='Off')sw(apcu_fetch('itv'),'On','TV');
if(apcu_fetch('zon')<100&&$s['tvled']=='Off')sw(apcu_fetch('itvled'),'On','tvled');
elseif($s['tv']=='On'&&$s['tvled']=='Off')sw(apcu_fetch('itvled'),'On','tvled');
$ctx=stream_context_create(array('http'=>array('timeout'=>3)));
file_get_contents('http://192.168.2.4/MainZone/index.put.asp?cmd0=PutZone_InputFunction/SAT/CBL',false,$ctx);
usleep(800000);
file_get_contents('http://192.168.2.4/MainZone/index.put.asp?cmd0=PutMasterVolumeSet/-42.0',false,$ctx);