<?php
if($s['denon']=='Off')sw($i['denon'],'On','Denon');
if($s['tv']=='On')sw($i['tv'],'Off','TV');
if($s['zon']>0){
	if($s['kristal']=='On')sw($i['kristal'],'Off','Kristal');
	if($s['tvled']=='On')sw($i['tvled'],'Off','tvled');
}
file_get_contents('http://192.168.2.4/MainZone/index.put.asp?cmd0=PutMasterVolumeSet/-50.0',false,$ctx);usleep(800000);
file_get_contents('http://192.168.2.4/MainZone/index.put.asp?cmd0=PutZone_InputFunction/TUNER',false,$ctx);